### ISSUE TITLE
from_fen doesnt work as expected

### ISSUE THREAD

**Issue by timglabisch** [jordanbray/chess#2]
i tryed to copy the fen example from https://de.wikipedia.org/wiki/Forsyth-Edwards-Notation

```
let board = Board::from_fen("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1".to_string()).expect("build board from fen");
```

i expected that this should just work, but instead the code panics.

**Comment by jordanbray** [comment]
I imagine you didn't call the initialize function chess::construct()

This function initializes some lookup tables for chess move generation.

If that doesn't work please let me know and I'll look deeper into it.

**Comment by timglabisch** [comment]
thanks a lot, now everything is fine =)
