### ISSUE TITLE
Typo in doc for new_legal(...)

### ISSUE THREAD

**Issue by jcriddle4** [jordanbray/chess#23]
In the documentation I think this  is supposed to be?

let mut iterable = MoveGen::new_legal(board, true);
...
let mut iterable = MoveGen::new_legal(**&board**);
....

**Comment by jordanbray** [comment]
I'm having a hard time finding where this is.  The old version used to take a boolean, but not anymore.  Can you link me to the page where you found that?  I'm hoping it turns out to be an old docs.rs link.

**Comment by jcriddle4** [comment]
https://github.com/jordanbray/chess

**Comment by jordanbray** [comment]
Ahh, lol.  I didn't check the readme.

**Comment by jordanbray** [comment]
I fixed it.  Thanks.
