### ISSUE TITLE
Build fails on arm (raspberry pi)

### ISSUE THREAD

**Issue by UlisseMini** [jordanbray/chess#26]
```
   Compiling chess v3.1.1
error[E0432]: unresolved import `std::arch::x86_64`
 --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/chess-3.1.1/src/gen_tables/bmis.rs:1:16
  |
1 | use std::arch::x86_64::_pext_u64;
  |                ^^^^^^ could not find `x86_64` in `arch`
```

If I have time i'll PR a fix, from my limited understanding I think this is only there for efficiency so it should be as simple as not importing for arm.

edit: Maybe consider using https://docs.rs/bitintr

**Comment by jordanbray** [comment]
I *believe* the version on github resolves this.  I don't have a rpi handy to test it, though.  I may get one working in a few days.

**Comment by UlisseMini** [comment]
Will test again with the github version when I get home and can use my RPI.

**Comment by UlisseMini** [comment]
Sorry for the delay, here is the result of trying to compile https://hastebin.com/alibuwahur

I don't think it's chess's fault for the failed build, I'll try and fix it incase its on my end.

**Comment by jordanbray** [comment]
Ahh, OK.  I'm gonna need to set up a raspberry pi or something to debug this one.  I had originally assumed it was just the BMI2 stuff, but it appears I've got some endian-ness stuff to fix in the magic bitboards implementation.

Thanks for reporting it.  I'll set up a pi (I think I have one around here somewhere) and get it figured out.

**Comment by jordanbray** [comment]
Long time no fix.  So, I finally got all the arm build issues resolved.  This is not pushed up to crates.io yet, but it should be in a few days (personal server is down).  Leaving open until it is fully resolved.
