### ISSUE TITLE
Release 3.2?

### ISSUE THREAD

**Issue by brunocodutra** [jordanbray/chess#34]
> Sorry for the empty description originally, I fat-fingered the return key before I had the chance to type anything.

Really appreciate the hard-work you and others have put into this crate.

There were a couple of features added after the last release; of particular interest to me would be the implementation of [`ForStr for ChessMove`](https://github.com/jordanbray/chess/commit/70461cafa92d3995fd14256c50526e1060bbb80f), but commit 6693cacb2e77297b40349096f1aabbdb7baf0f66 in particular looks packed with improvements as well.

Is there a target date for the next release?

**Comment by jordanbray** [comment]
There isn't a date set.  I've honestly not had a lot of free time to maintain this lately (I had a baby).  Hopefully I'll get back into the swing of things sometime.

May *plan* was to release a new version with the `chess_uci` package that I've been working on, but I haven't had time to finish that, so maybe pushing out a new version is appropriate.

I'll take a look at the code in the next day or two and clean anything up that needs it, then push out a new version.

**Comment by jordanbray** [comment]
Done.  Along with all the fixes from the community.
