### ISSUE TITLE
Use of std::mem::transmute in Rank and File is undefined behaviour

### ISSUE THREAD

**Issue by analog-hors** [jordanbray/chess#52]
The [reference for type representations](https://doc.rust-lang.org/reference/type-layout.html#the-default-representation) states that
> Nominal types **without a `repr` attribute** have the default representation. Informally, this representation is also called the `rust` representation.
>
> There are **no guarantees of data layout** made by this representation.

However, the `Rank` and `File` types rely on a defined layout due to the use of `std::mem::transmute`:
https://github.com/jordanbray/chess/blob/ad138579074ca1b0a88514626016d8e0b72d4ed3/src/rank.rs#L37-L39
https://github.com/jordanbray/chess/blob/ad138579074ca1b0a88514626016d8e0b72d4ed3/src/file.rs#L36-L38

**Comment by jordanbray** [comment]
Resolved.
