### ISSUE TITLE
CastleRights::from_index and CastleRights::rook_square_to_castle_rights are unsound

### ISSUE THREAD

**Issue by analog-hors** [jordanbray/chess#53]
`CastleRights::from_index` and `CastleRights::rook_square_to_castle_rights` are both unsound; They can cause undefined behavior on certain inputs while not marked as `unsafe`. The documentation is also misleading, instead saying that it will panic.
https://github.com/jordanbray/chess/blob/ad138579074ca1b0a88514626016d8e0b72d4ed3/src/castle_rights.rs#L97-L106
https://github.com/jordanbray/chess/blob/ad138579074ca1b0a88514626016d8e0b72d4ed3/src/castle_rights.rs#L146-L154

**Comment by jordanbray** [comment]
Both are resolved in master.
