### ISSUE TITLE
Out of bounds square can cause out of bounds access.

### ISSUE THREAD

**Issue by analog-hors** [jordanbray/chess#56]
```rs
fn main() {
    println!("{}", chess::get_king_moves(chess::EMPTY.to_square()));
}
```
prints garbage:
```rs
. . . . . . X X 
X X X . X . . .
X X . X X X X .
. . . . X . X .
. X X . X X X X
X X X X X X X .
. . . . . . . .
. . . . . . . .
```
`BitBoard::to_square` creates an out of bounds `Square(64)` on an empty bitboard. This can be used to access out of bounds memory.
Another somewhat irrelevant thing that can be considered is making `Square` an `enum` instead. This would allow the compiler to automatically elide all bounds checks when indexing by `Square`s. It would allow it to be used for niche space optimizations.

**Comment by jordanbray** [comment]
The UB is resolved, but making square an enum is a good idea.
